version: '3'

services:
  db:
    image: mysql
    container_name: django-mysql
    restart: always
    volumes:
      - ./database:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "django"
    ports:
      - "3306:3306"